#@TYPE: Machine
#@NAME: Digilent Zybo Z7
#@DESCRIPTION: Digilent Zybo Z7 (Zynq-7000 Cortex-A9) machine for TGBS

require conf/machine/include/arm/armv7a/tune-cortexa9.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-tgbs"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"

KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE = "xilinx/zynq-zybo-z7.dtb"

UBOOT_MACHINE = "xilinx_zynq_virt_defconfig"
UBOOT_SUFFIX = "img"
UBOOT_ENTRYPOINT = "0x00008000"
UBOOT_LOADADDRESS = "0x00008000"
SPL_BINARY = "spl/boot.bin"

UBOOT_EXTLINUX = "1"
UBOOT_EXTLINUX_ROOT = "root=/dev/mmcblk0p2"
UBOOT_EXTLINUX_KERNEL_IMAGE = "/zImage"
UBOOT_EXTLINUX_FDT = "/system.dtb"
UBOOT_EXTLINUX_CONSOLE = "console=ttyPS0,115200"

SERIAL_CONSOLES = "115200;ttyPS0"

MACHINE_FEATURES = "kernel26 usbhost vfat ext2 ethernet"
EXTRA_IMAGEDEPENDS += "u-boot"

IMAGE_FSTYPES += "wic wic.bmap"
WKS_FILE = "zybo-z7.wks"
IMAGE_BOOT_FILES = " \
    boot.bin \
    u-boot.img \
    zImage \
    zynq-zybo-z7.dtb;system.dtb \
    extlinux.conf;extlinux/extlinux.conf \
"
