# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-kdebug"
BBFILE_PATTERN_meta-kdebug = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-kdebug = "7"

LAYERDEPENDS_meta-kdebug = "core"
LAYERSERIES_COMPAT_meta-kdebug = "scarthgap"

DEBUG_KERNEL_FILES_DIR := "${LAYERDIR}/classes/files"
INHERIT += "debug-kernel"
